# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SoccerTrac' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for SoccerTrac
  pod 'Alamofire', '~> 4.0'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
#  target 'SoccerTracTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#  target 'SoccerTracUITests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

end
